"""
document_export_tools.py — Generate PDF reports and Excel spreadsheets
from the user's actual financial data.

Tools:
    generate_pdf_report     — Multi-section PDF financial report (portfolio,
                              budget summary, goals) using reportlab
    generate_excel_report   — Multi-sheet Excel workbook using openpyxl

Both tools return a base64-encoded file that the frontend downloads.
The agent returns: FILE_BASE64_PDF:<b64> or FILE_BASE64_XLSX:<b64>
The frontend detects these prefixes and triggers a file download.
"""

import base64
import io
from datetime import datetime

from langchain_core.tools import tool
from src.utils.logger import get_logger

logger = get_logger(__name__)

# ── Colour constants ──────────────────────────────────────────
_GOLD   = (0.902, 0.725, 0.176)   # #E6B92C
_DARK   = (0.071, 0.094, 0.149)   # #121826
_BLUE   = (0.102, 0.337, 0.859)   # #1A56DB
_GREEN  = (0.020, 0.475, 0.333)   # #057A55
_RED    = (0.784, 0.118, 0.118)   # #C81E1E
_GREY   = (0.933, 0.937, 0.945)   # #EEF0F1
_TEXT   = (0.067, 0.067, 0.067)   # #111111


@tool
def generate_pdf_report(
    user_id: str,
    user_name: str = "User",
    include_portfolio: bool = True,
    include_budget: bool = True,
    include_goals: bool = True,
) -> str:
    """
    Generate a professional PDF financial report containing the user's
    portfolio positions, budget summary, and financial goals.

    user_id: The current user's ID
    user_name: User's display name for the report header
    include_portfolio: Include portfolio section (default True)
    include_budget: Include budget summary section (default True)
    include_goals: Include financial goals section (default True)

    Returns a base64-encoded PDF as FILE_BASE64_PDF:<b64>.
    The frontend will trigger a download automatically.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
        )
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.enums import TA_CENTER, TA_LEFT
        from src.database.operations import get_portfolio, get_budget_entries, get_financial_goals

        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf, pagesize=A4,
            rightMargin=2*cm, leftMargin=2*cm,
            topMargin=2*cm, bottomMargin=2*cm,
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "Title", parent=styles["Title"],
            fontSize=22, textColor=colors.HexColor("#121826"),
            spaceAfter=4, alignment=TA_CENTER,
        )
        subtitle_style = ParagraphStyle(
            "Subtitle", parent=styles["Normal"],
            fontSize=10, textColor=colors.HexColor("#6B7280"),
            spaceAfter=2, alignment=TA_CENTER,
        )
        section_style = ParagraphStyle(
            "Section", parent=styles["Heading2"],
            fontSize=13, textColor=colors.HexColor("#1A56DB"),
            spaceBefore=16, spaceAfter=6, borderPad=4,
        )
        body_style = ParagraphStyle(
            "Body", parent=styles["Normal"],
            fontSize=9, textColor=colors.HexColor("#374151"),
            spaceAfter=4, leading=14,
        )

        now = datetime.now().strftime("%B %d, %Y")
        story = []

        # ── Header ─────────────────────────────────────────────
        story.append(Paragraph("💎 FinAdvisor AI", title_style))
        story.append(Paragraph(f"Financial Report — {now}", subtitle_style))
        story.append(Paragraph(f"Prepared for: {user_name}", subtitle_style))
        story.append(HRFlowable(width="100%", thickness=1.5,
                                color=colors.HexColor("#E6B92C"), spaceAfter=12))

        # ── Disclaimer ─────────────────────────────────────────
        disclaimer = ParagraphStyle(
            "Disclaimer", parent=styles["Normal"],
            fontSize=7.5, textColor=colors.HexColor("#9CA3AF"),
            backColor=colors.HexColor("#F9FAFB"),
            borderPad=6, spaceAfter=12, leading=12,
        )
        story.append(Paragraph(
            "⚠️ This report is generated by FinAdvisor AI and is for informational purposes only. "
            "It does not constitute financial advice. Please consult a qualified financial advisor "
            "before making any significant financial decisions.",
            disclaimer
        ))

        def _table_header_style(col_count):
            return TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1A56DB")),
                ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
                ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE",   (0, 0), (-1, 0), 9),
                ("ALIGN",      (0, 0), (-1, 0), "CENTER"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1),
                 [colors.HexColor("#F9FAFB"), colors.white]),
                ("FONTNAME",   (0, 1), (-1, -1), "Helvetica"),
                ("FONTSIZE",   (0, 1), (-1, -1), 8.5),
                ("ALIGN",      (1, 1), (-1, -1), "RIGHT"),
                ("ALIGN",      (0, 1), (0,  -1), "LEFT"),
                ("GRID",       (0, 0), (-1, -1), 0.4, colors.HexColor("#E5E7EB")),
                ("ROWPADDING", (0, 0), (-1, -1), 5),
            ])

        # ── Portfolio ──────────────────────────────────────────
        if include_portfolio:
            story.append(Paragraph("📈 Portfolio Positions", section_style))
            positions = get_portfolio(user_id)
            if positions:
                data = [["Ticker", "Type", "Shares", "Avg Price", "Est. Value"]]
                for p in positions:
                    shares = float(p.get("shares", 0))
                    price  = float(p.get("avg_buy_price", 0))
                    val    = shares * price
                    data.append([
                        p.get("ticker", ""),
                        p.get("asset_type", "stock").title(),
                        f"{shares:,.4f}",
                        f"${price:,.2f}",
                        f"${val:,.2f}",
                    ])
                total_val = sum(float(p.get("shares",0)) * float(p.get("avg_buy_price",0)) for p in positions)
                data.append(["", "", "", "Total", f"${total_val:,.2f}"])

                t = Table(data, colWidths=[3.5*cm, 3*cm, 3*cm, 3.5*cm, 3.5*cm])
                style = _table_header_style(5)
                style.add("FONTNAME",  (0, len(data)-1), (-1, len(data)-1), "Helvetica-Bold")
                style.add("BACKGROUND",(0, len(data)-1), (-1, len(data)-1), colors.HexColor("#EEF2FF"))
                t.setStyle(style)
                story.append(t)
            else:
                story.append(Paragraph("No portfolio positions found.", body_style))

        # ── Budget ─────────────────────────────────────────────
        if include_budget:
            story.append(Paragraph("💰 Budget Summary (Current Month)", section_style))
            month = datetime.now().strftime("%Y-%m")
            entries = get_budget_entries(user_id, month)
            if entries:
                income  = sum(float(e.get("amount",0)) for e in entries if e.get("entry_type") == "income")
                expense = sum(float(e.get("amount",0)) for e in entries if e.get("entry_type") == "expense")
                net = income - expense

                summary_data = [
                    ["Metric", "Amount"],
                    ["Total Income",   f"${income:,.2f}"],
                    ["Total Expenses", f"${expense:,.2f}"],
                    ["Net Balance",    f"${net:,.2f}"],
                ]
                t = Table(summary_data, colWidths=[8*cm, 8*cm])
                style = _table_header_style(2)
                net_color = colors.HexColor("#057A55") if net >= 0 else colors.HexColor("#C81E1E")
                style.add("TEXTCOLOR", (1, 3), (1, 3), net_color)
                style.add("FONTNAME",  (0, 3), (-1, 3), "Helvetica-Bold")
                t.setStyle(style)
                story.append(t)
                story.append(Spacer(1, 8))

                # Category breakdown
                cats = {}
                for e in entries:
                    if e.get("entry_type") == "expense":
                        cat = e.get("category", "Other")
                        cats[cat] = cats.get(cat, 0) + float(e.get("amount", 0))
                if cats:
                    story.append(Paragraph("Expense Breakdown by Category:", body_style))
                    cat_data = [["Category", "Amount", "% of Expenses"]]
                    for cat, amt in sorted(cats.items(), key=lambda x: -x[1]):
                        pct = (amt / expense * 100) if expense > 0 else 0
                        cat_data.append([cat, f"${amt:,.2f}", f"{pct:.1f}%"])
                    t2 = Table(cat_data, colWidths=[7*cm, 5*cm, 4.5*cm])
                    t2.setStyle(_table_header_style(3))
                    story.append(t2)
            else:
                story.append(Paragraph("No budget entries found for this month.", body_style))

        # ── Goals ──────────────────────────────────────────────
        if include_goals:
            story.append(Paragraph("🎯 Financial Goals", section_style))
            goals = get_financial_goals(user_id)
            if goals:
                data = [["Goal", "Target", "Saved", "Progress", "Deadline"]]
                for g in goals:
                    target  = float(g.get("target_amount", 0))
                    current = float(g.get("current_amount", 0))
                    pct     = (current / target * 100) if target > 0 else 0
                    deadline = g.get("target_date", "—") or "—"
                    data.append([
                        g.get("name", ""),
                        f"${target:,.2f}",
                        f"${current:,.2f}",
                        f"{pct:.1f}%",
                        deadline,
                    ])
                t = Table(data, colWidths=[5*cm, 3.5*cm, 3.5*cm, 2.5*cm, 3*cm])
                t.setStyle(_table_header_style(5))
                story.append(t)
            else:
                story.append(Paragraph("No financial goals found.", body_style))

        # ── Footer ─────────────────────────────────────────────
        story.append(Spacer(1, 16))
        story.append(HRFlowable(width="100%", thickness=0.5,
                                color=colors.HexColor("#E5E7EB")))
        footer_style = ParagraphStyle(
            "Footer", parent=styles["Normal"],
            fontSize=7, textColor=colors.HexColor("#9CA3AF"),
            alignment=TA_CENTER, spaceBefore=6,
        )
        story.append(Paragraph(
            f"Generated by FinAdvisor AI · {now} · For informational purposes only",
            footer_style
        ))

        doc.build(story)
        buf.seek(0)
        b64 = base64.b64encode(buf.read()).decode("utf-8")

        logger.info("pdf_report_generated", user_id=user_id)
        return f"FILE_BASE64_PDF:{b64}"

    except ImportError:
        return (
            "❌ PDF generation requires the 'reportlab' library. "
            "Ask your administrator to run: pip install reportlab"
        )
    except Exception as e:
        logger.error("pdf_report_failed", error=str(e))
        return f"❌ Failed to generate PDF report: {str(e)}"


@tool
def generate_excel_report(
    user_id: str,
    user_name: str = "User",
) -> str:
    """
    Generate an Excel workbook (.xlsx) containing the user's portfolio,
    budget entries, financial goals, and a summary dashboard sheet.

    user_id: The current user's ID
    user_name: User's display name for the report header

    Returns a base64-encoded .xlsx file as FILE_BASE64_XLSX:<b64>.
    The frontend will trigger a download automatically.
    """
    try:
        from openpyxl import Workbook
        from openpyxl.styles import (
            Font, PatternFill, Alignment, Border, Side, numbers
        )
        from openpyxl.utils import get_column_letter
        from src.database.operations import get_portfolio, get_budget_entries, get_financial_goals

        wb = Workbook()

        # ── Style helpers ──────────────────────────────────────
        HEADER_FILL = PatternFill("solid", fgColor="1A56DB")
        HEADER_FONT = Font(bold=True, color="FFFFFF", size=10)
        TITLE_FONT  = Font(bold=True, size=14, color="121826")
        LABEL_FONT  = Font(bold=True, size=10, color="374151")
        ALT_FILL    = PatternFill("solid", fgColor="F3F4F6")
        TOTAL_FILL  = PatternFill("solid", fgColor="EEF2FF")
        TOTAL_FONT  = Font(bold=True, size=10, color="1A56DB")
        CENTER      = Alignment(horizontal="center", vertical="center")
        LEFT        = Alignment(horizontal="left",   vertical="center")
        RIGHT       = Alignment(horizontal="right",  vertical="center")
        thin        = Side(style="thin", color="E5E7EB")
        BORDER      = Border(left=thin, right=thin, top=thin, bottom=thin)

        def _header_row(ws, row, cols):
            for col, val in enumerate(cols, 1):
                c = ws.cell(row=row, column=col, value=val)
                c.fill = HEADER_FILL
                c.font = HEADER_FONT
                c.alignment = CENTER
                c.border = BORDER

        def _data_row(ws, row, vals, alt=False):
            fill = ALT_FILL if alt else None
            for col, val in enumerate(vals, 1):
                c = ws.cell(row=row, column=col, value=val)
                c.alignment = RIGHT if isinstance(val, (int, float)) else LEFT
                c.border = BORDER
                if fill:
                    c.fill = fill

        def _auto_width(ws):
            for col in ws.columns:
                max_len = max((len(str(c.value or "")) for c in col), default=10)
                ws.column_dimensions[get_column_letter(col[0].column)].width = min(max_len + 4, 40)

        now_str = datetime.now().strftime("%B %d, %Y")

        # ─── Sheet 1: Summary Dashboard ───────────────────────
        ws = wb.active
        ws.title = "Summary"
        ws.sheet_view.showGridLines = False

        ws["A1"] = "💎 FinAdvisor AI — Financial Report"
        ws["A1"].font = TITLE_FONT
        ws["A2"] = f"Prepared for: {user_name}   |   Generated: {now_str}"
        ws["A2"].font = Font(size=10, color="6B7280")
        ws["A4"] = "⚠️ For informational purposes only. Not financial advice."
        ws["A4"].font = Font(size=9, color="9CA3AF", italic=True)

        positions = get_portfolio(user_id)
        month     = datetime.now().strftime("%Y-%m")
        entries   = get_budget_entries(user_id, month)
        goals     = get_financial_goals(user_id)

        portfolio_val = sum(float(p.get("shares",0)) * float(p.get("avg_buy_price",0)) for p in positions)
        income        = sum(float(e.get("amount",0)) for e in entries if e.get("entry_type") == "income")
        expenses      = sum(float(e.get("amount",0)) for e in entries if e.get("entry_type") == "expense")
        net           = income - expenses

        ws["A6"] = "Key Metrics"; ws["A6"].font = LABEL_FONT
        metrics = [
            ("Portfolio Value (cost basis)", f"${portfolio_val:,.2f}"),
            ("Monthly Income",               f"${income:,.2f}"),
            ("Monthly Expenses",             f"${expenses:,.2f}"),
            ("Monthly Net Balance",          f"${net:,.2f}"),
            ("Active Goals",                 str(len(goals))),
            ("Portfolio Positions",          str(len(positions))),
        ]
        for i, (label, val) in enumerate(metrics, 7):
            ws[f"A{i}"] = label
            ws[f"B{i}"] = val
            ws[f"A{i}"].font = Font(size=10, color="374151")
            ws[f"B{i}"].font = Font(size=10, bold=True, color="1A56DB")
        _auto_width(ws)

        # ─── Sheet 2: Portfolio ────────────────────────────────
        ws2 = wb.create_sheet("Portfolio")
        ws2.sheet_view.showGridLines = False
        ws2["A1"] = "Portfolio Positions"
        ws2["A1"].font = TITLE_FONT
        ws2["A2"] = now_str
        ws2["A2"].font = Font(size=9, color="9CA3AF")

        headers = ["Ticker", "Asset Type", "Shares", "Avg Buy Price", "Est. Value", "Notes"]
        _header_row(ws2, 4, headers)
        for i, p in enumerate(positions, 5):
            shares = float(p.get("shares", 0))
            price  = float(p.get("avg_buy_price", 0))
            val    = shares * price
            _data_row(ws2, i, [
                p.get("ticker", ""),
                p.get("asset_type", "stock").title(),
                shares, price, val,
                p.get("notes", ""),
            ], alt=(i % 2 == 0))

        if positions:
            total_row = len(positions) + 5
            ws2.cell(total_row, 1, "TOTAL").font = TOTAL_FONT
            ws2.cell(total_row, 5, portfolio_val).font = TOTAL_FONT
            ws2.cell(total_row, 5).fill = TOTAL_FILL

        _auto_width(ws2)

        # ─── Sheet 3: Budget ───────────────────────────────────
        ws3 = wb.create_sheet("Budget")
        ws3.sheet_view.showGridLines = False
        ws3["A1"] = f"Budget Entries — {month}"
        ws3["A1"].font = TITLE_FONT

        _header_row(ws3, 3, ["Date", "Type", "Category", "Subcategory", "Amount", "Description"])
        for i, e in enumerate(entries, 4):
            _data_row(ws3, i, [
                e.get("entry_date", ""),
                e.get("entry_type", "").title(),
                e.get("category", ""),
                e.get("subcategory", ""),
                float(e.get("amount", 0)),
                e.get("description", ""),
            ], alt=(i % 2 == 0))

        if entries:
            summary_start = len(entries) + 6
            ws3.cell(summary_start,   1, "Income Total").font  = LABEL_FONT
            ws3.cell(summary_start,   2, income).font          = Font(bold=True, color="057A55")
            ws3.cell(summary_start+1, 1, "Expense Total").font = LABEL_FONT
            ws3.cell(summary_start+1, 2, expenses).font        = Font(bold=True, color="C81E1E")
            ws3.cell(summary_start+2, 1, "Net Balance").font   = LABEL_FONT
            ws3.cell(summary_start+2, 2, net).font             = Font(
                bold=True, color="057A55" if net >= 0 else "C81E1E"
            )

        _auto_width(ws3)

        # ─── Sheet 4: Goals ────────────────────────────────────
        ws4 = wb.create_sheet("Goals")
        ws4.sheet_view.showGridLines = False
        ws4["A1"] = "Financial Goals"
        ws4["A1"].font = TITLE_FONT

        _header_row(ws4, 3, ["Goal Name", "Target Amount", "Current Amount", "Progress %", "Deadline", "Status"])
        for i, g in enumerate(goals, 4):
            target  = float(g.get("target_amount", 0))
            current = float(g.get("current_amount", 0))
            pct     = round((current / target * 100), 1) if target > 0 else 0
            _data_row(ws4, i, [
                g.get("name", ""),
                target, current, pct,
                g.get("target_date", "") or "",
                g.get("status", "active").title(),
            ], alt=(i % 2 == 0))

        _auto_width(ws4)

        # ── Serialise ──────────────────────────────────────────
        buf = io.BytesIO()
        wb.save(buf)
        buf.seek(0)
        b64 = base64.b64encode(buf.read()).decode("utf-8")

        logger.info("excel_report_generated", user_id=user_id)
        return f"FILE_BASE64_XLSX:{b64}"

    except ImportError:
        return (
            "❌ Excel generation requires the 'openpyxl' library. "
            "Ask your administrator to run: pip install openpyxl"
        )
    except Exception as e:
        logger.error("excel_report_failed", error=str(e))
        return f"❌ Failed to generate Excel report: {str(e)}"